config/routes.rb
Rails.application.routes.draw do

  root to: 'registration#home'

  resources :gossips 
  resources :users, only: [:new, :create]
  get "users/login", to: "users#login"
  post "users/login", to: "users#check"

  resources :gossips do
    resources :comments, only: [:new, :create, :index, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user 
    belongs_to :gossip 
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    has_many :comments 
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user 
    belongs_to :gossip
    belongs_to :comment 
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def index 
        @comments = Comment.all 
    end 

    def new
        @comment = Comment.new 
    end 

    def create
        @gossip = Gossip.find(params[:gossip_id])
    
        @comment = @gossip.comments.new(comment_params)
        @comment.user_id = session[:user_id]
        @comment.save 
        redirect_to gossip_path(@gossip)
    end

      private
    def comment_params
        params.require(:comment).permit(:content)
    end

    def show
        @comment = Comment.find(id: params[:comment_id])
    end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

    def index 
        @gossips = Gossip.all 
    end 

    def new 
         @gossip = Gossip.new 
    end 
        
    def create 
        @gossip = Gossip.new 
        @gossip.title = params["gossip"][:title]
        @gossip.content = params["gossip"][:content]
        @gossip.save 
        redirect_to @gossip 
    end 


    def show 
       @gossip = Gossip.find(params[:id])
    end 

    def edit 
        @gossip = Gossip.find(params[:id])
    end 

    def update 
        @gossip = Gossip.find(params[:id])
        gossip_params = params.require(:gossip).permit(:title, :content)
        @gossip.update(gossip_params)
        redirect_to gossip_path 
    end 

    def destroy 
        @gossip = Gossip.find(params[:id])
        @gossip.destroy
        redirect_to gossips_path
    end 

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

    def index 
        @likes = Like.all 
    end 

    def new
        @like = Like.new 
    end 

    def create
        @like = Like.find(params[:like_id])
        @gossip = @gossip.likes.create(like_params)
        redirect_to gossip_path(@gossip)
    end
     
      private
        def like_params
          params.require(:like).permit(:user_id, :body)
        end

    def show 
         @like = Like.find(params[:id])
    end 
    
end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController


    def home
        
    end 

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

    def home 

    end 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def home
    end

    def login 
        
    end 

    def new
        @user= User.new
    end

	def create
        user = params[:user]
        @user = User.create(name: user[:name], email: user[:email], password: user[:password])
        flash[:info] = "Bienvenue #{@user.name} !"
        redirect_to gossips_path
	end

	def check
	    user = params
	    @current_user = User.where(name: user[:name], password: user[:password]).first
        if @current_user
            session[:user_id] = @current_user.id
        flash[:info] = "Bienvenue #{@current_user.name} !"
        redirect_to gossips_path 
        else
                session[:user_id] = nil 
        flash[:info] = "Échec de la connexion,veuillez réessayer de se connecter"
        redirect_to "/users/login"
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/gossips_comments_helper.rb
module GossipsCommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/index.html.erb


    <% @comments.each do |comment| %>
    <h2><%= comment.content %></h2>
    <% end %> 



    





app/views/comments/new.html.erb

        <%= form_for @comment do |f| %>
        <div class =”form-group”>
        <div class ='container'>
        <br><label>Formulaire de commentaire</label></br>
        Ton com's baby : <br><%= f.text_field :content  %></br>
        <%= f.submit "Soumettre mon formulaire" %>
        </div>
        </div> 
        <% end %>














  















       







app/views/comments/show.html.erb
<h1><% @gossips.each do |comment| %></h1>
<h2><%= comment.content %></h2>
<p>
<%= link_to "Revenir à l'acceuil (formulaire)", comments_path %>
<% end %> 
</p>


<% @gossip.comments.each do |comment| %>
	<%= comment.anonymous_commentor %>
	<p><%= comment.content %><p><br>
<% end %>










app/views/gossips/edit.html.erb

<h1> Editer Article</h1>

<%= form_for @gossip do |f| %> 
    
    <div class="form-group">

    <label> Modifier le titre du gossip</label>

    <%= f.text_field :title, class: 'form-control' %>
    </div> 

    <div class="form-group">

    <label> Modifier le contenu du gossip</label>
    <%= f.text_area :content, class: 'form-control' %> 
    </div> 

    <div class="form-group">
        <button type="submit" class="btn btn-primary"> Modifier le gossip</button>
    </div> 

<% end %> 



app/views/gossips/index.html.erb
    <p> 
    <a href="<%= new_gossip_path %>" class="btn btn-success">Créer un gossip</a> 
    </p> 


    <% @gossips.each do |gossip| %>
    <h2><%= gossip.title %></h2>
    <p><%= gossip.content %></p>

    <p> 
    <a href="<%= gossip_path(gossip.id)%>" class= "btn btn-primary">Consulter ce gossip et ajouter un commentaire</a>
    <a href="<%= edit_gossip_path(gossip.id)%>" class= "btn btn-default">Modifier ce gossip</a>
    <a href="<%= gossip_path(gossip.id) %>" class="btn btn-danger" data-confirm="Calme toi mon petit ! Êtes-vous sur de supprimer ce gossip?" data-method="DELETE" >Supprimer</a> 
    </p> 

    <% end %>


















app/views/gossips/new.html.erb

    <%= form_for @gossip do |f| %>
    <div class =”form-group”>
    <br><label>Formulaire de création de Gossip</label></br>
    Titre du gossip : <br><%= f.text_field :title  %></br>
    Contenu du gossip : <br><%= f.text_field :content %></br>
    <%= f.submit "Soumettre mon formulaire" %>
    </div>
    <% end %> 


    



    





app/views/gossips/show.html.erb
    <h3>Le fameux petit gossip : </h3>
        <br><%= @gossip.title %></br>
        <br><%= @gossip.content %></br>
    <%= link_to "Revenir à l'acceuil (formulaire)", gossips_path %>
    </p> 


    <h3>Hop, hop, hop pour ajouter un commentaire c'est ici !</h3>
    <%= form_with(model: [ @user, @gossip, @gossip.comments.build ], local: true) do |form| %>
    <p>
       Ton commentaire :<%= form.text_area :content %>
    </p>
    <p>
        <%= form.submit %>
    </p>
    <% end %>
    














app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Bienvenue !</h1>
  <h3>
    Ici, tu peux retrouver les moussaillons 🎓
  </h3>
  <%= link_to "Enregistre-toi !", new_user_path, class: "btn btn-lg btn-primary" %>
</div>




app/views/users/home.html.erb
<div class="center jumbotron">
  <h1>Bienvenue !</h1>
  <h3>
    Nouvel utilisateur? 🎓
  </h3>
  <%= link_to "Enregistre-toi!", new_user_path, class: "btn btn-lg btn-primary" %>

  <h3>
  <%= link_to "Connecte-toi! !", users_login_path, class: "btn btn-lg btn-primary" %>
  </h3> 
</div>


<% if session[:user_id] != nil %>
<h1> Tu peux maintenant acceder aux gossips </h1>
<a href= "#">Voir gossip
<% else %>
  <h1>Bienvenue visiteur anonyme !</h1>
  <a href="/users/login">S'identifier</a>
<% end %>













app/views/users/login.html.erb
<h1>Veuillez rentrer votre mail et votre mot de passe pour vous connecter</h1>
<a href="/">Retourner à l'accueil</a>
<%= form_tag "/users/login", method: :post do %>
  nom : <input type="text" name="name" />
  mot de passe: <input type="password" name="password" />
  <input type="submit" value="Se connecter" />
<% end %>





app/views/users/new.html.erb
<div class="container">
<br>

<h1>Veuilez remplir les informations suivantes pour créer votre compte</h2>
<%= form_for @user, url: {action: "create"} do |f| %>
   	Pseudo <%= f.text_field :name, class:"form-control", placeholder:"pseudo"%><br>
  	Email <%= f.text_field :email, class: "form-control", placeholder:"email"%><br>
  	Mot de Passe <%= f.text_area :password, class: "form-control", placeholder:"mot de passe"%><br>
  	<%= f.submit "Créer mon compte"%>
<% end %>


</div>






    
